name: Build Release

on:
  workflow_dispatch:

jobs:
  build3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/ShortUrl.csproj
    - name: Build
      run: dotnet build src/ShortUrl.csproj -f netcoreapp3.1 -c Release -o ${{env.DOTNET_ROOT}}/publish
    - name: Delete dev files
      run: rm -fr ${{env.DOTNET_ROOT}}/publish/Properties ${{env.DOTNET_ROOT}}/publish/SecretNest.ShortUrl.pdb ${{env.DOTNET_ROOT}}/publish/SecretNest.ShortUrl.runtimeconfig.dev.json
    - name: Tar
      run: tar -cvf Release.NetCore3.1.tar.gz -C ${{env.DOTNET_ROOT}}/publish .
    - name: Zip
      uses: montudor/action-zip@v0.1.1
      with:
        args: zip -qq -r Release.NetCore3.1.zip ${{env.DOTNET_ROOT}}/publish/*.*
    - name: temp
      uses: actions/upload-artifact@v2
      with:
        name: release.tar.gz
        path: Release.NetCore3.1.tar.gz
    - name: temp2
      uses: actions/upload-artifact@v2
      with:
        name: release.zip
        path: Release.NetCore3.1.zip
