name: Build Release

on:
  workflow_dispatch:

jobs:
  build3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/ShortUrl.csproj
    - name: Build
      run: dotnet build src/ShortUrl.csproj -f netcoreapp3.1 -c Release -o ${{env.DOTNET_ROOT}}/publish
    - name: dir
      run: dir ${{env.DOTNET_ROOT}}/publish
